export const canonicalPermissions = [
  "users.view",
  "users.manage",
  "roles.view",
  "roles.manage",
  "profile.view",
  "profile.update",
  "students.view",
  "students.manage",
  "teachers.view",
  "teachers.manage",
  "teacher_scope.view_assigned",
  "student_progress.view",
  "learning.preview_as_student",
  "schedule.view",
  "schedule.manage",
  "homework.view",
  "homework.assign",
  "homework.submit",
  "billing.view",
  "billing.adjust",
  "payments.view",
  "payments.manage",
  "crm.access",
  "crm.leads.view",
  "crm.leads.manage",
  "word_cards.train",
  "word_cards.demo_train",
  "word_cards.manage",
  "content.manage",
  "notifications.view",
  "notifications.manage",
  "search.ui"
] as const;

export type CanonicalPermission = (typeof canonicalPermissions)[number];

export const legacyPermissionAliasKeys = [
  "admin.users.read",
  "admin.users.create",
  "admin.users.update",
  "admin.users.delete",
  "admin.teachers.read",
  "admin.teachers.update",
  "crm.leads.read",
  "crm.leads.update",
  "crm.leads.delete",
  "crm.settings.read",
  "crm.settings.update",
  "billing.admin.read",
  "billing.adjustments.create",
  "billing.reminders.manage",
  "billing.settings.update",
  "billing.summary.read",
  "learning.content.manage",
  "learning.tests.manage",
  "content.posts.manage",
  "notifications.admin.read",
  "notifications.admin.manage",
  "notifications.user.read",
  "schedule.lessons.read",
  "schedule.lessons.manage",
  "words.cardSets.manage"
] as const;

export const legacyPermissionAliases = [
  ["admin.users.read", "users.view"],
  ["admin.users.create", "users.manage"],
  ["admin.users.update", "users.manage"],
  ["admin.users.delete", "users.manage"],
  ["admin.teachers.read", "teachers.view"],
  ["admin.teachers.update", "teachers.manage"],
  ["crm.leads.read", "crm.leads.view"],
  ["crm.leads.update", "crm.leads.manage"],
  ["crm.leads.delete", "crm.leads.manage"],
  ["crm.settings.read", "crm.leads.view"],
  ["crm.settings.update", "crm.leads.manage"],
  ["billing.admin.read", "payments.view"],
  ["billing.adjustments.create", "billing.adjust"],
  ["billing.reminders.manage", "payments.manage"],
  ["billing.settings.update", "billing.adjust"],
  ["billing.summary.read", "billing.view"],
  ["learning.content.manage", "content.manage"],
  ["learning.tests.manage", "content.manage"],
  ["content.posts.manage", "content.manage"],
  ["notifications.admin.read", "notifications.manage"],
  ["notifications.admin.manage", "notifications.manage"],
  ["notifications.user.read", "notifications.view"],
  ["schedule.lessons.read", "schedule.view"],
  ["schedule.lessons.manage", "schedule.manage"],
  ["words.cardSets.manage", "word_cards.manage"]
] as const satisfies readonly (readonly [(typeof legacyPermissionAliasKeys)[number], CanonicalPermission])[];

export const runtimeCompatibilityPermissions = [
  "students.notes.read",
  "students.notes.write",
  "learning.placement.assign",
  "notifications.user.manage",
  "payments.checkout.create",
  "payments.history.read",
  "payments.status.read",
  "practice.attempts.submit",
  "schedule.followups.read",
  "schedule.followups.manage",
  "settings.profile.read",
  "settings.profile.update",
  "words.sessions.complete"
] as const;

export const runtimeOnlyPermissions = [] as const;

export const deprecatedPermissions = ["admin.dashboard.read"] as const;

export const permissions = [
  ...canonicalPermissions,
  ...legacyPermissionAliasKeys,
  ...runtimeCompatibilityPermissions,
  ...runtimeOnlyPermissions,
  ...deprecatedPermissions
] as const;

export const rbacAuthoritativePermissionAliases = [
  ["roles.view", "roles.view"],
  ["roles.manage", "roles.manage"],
  ["content.manage", "content.manage"],
  ["learning.content.manage", "content.manage"],
  ["learning.tests.manage", "content.manage"],
  ["content.posts.manage", "content.manage"],
  ["crm.leads.view", "crm.leads.view"],
  ["crm.leads.read", "crm.leads.view"],
  ["crm.settings.read", "crm.leads.view"],
  ["crm.leads.manage", "crm.leads.manage"],
  ["crm.leads.update", "crm.leads.manage"],
  ["crm.leads.delete", "crm.leads.manage"],
  ["crm.settings.update", "crm.leads.manage"],
  ["teachers.view", "teachers.view"],
  ["admin.teachers.read", "teachers.view"],
  ["teachers.manage", "teachers.manage"],
  ["admin.teachers.update", "teachers.manage"],
  ["users.view", "users.view"],
  ["admin.users.read", "users.view"],
  ["users.manage", "users.manage"],
  ["admin.users.create", "users.manage"],
  ["admin.users.update", "users.manage"],
  ["admin.users.delete", "users.manage"],
  ["profile.view", "profile.view"],
  ["settings.profile.read", "profile.view"],
  ["profile.update", "profile.update"],
  ["settings.profile.update", "profile.update"],
  ["students.view", "students.view"],
  ["students.manage", "students.manage"],
  ["teacher_scope.view_assigned", "teacher_scope.view_assigned"],
  ["student_progress.view", "student_progress.view"],
  ["learning.preview_as_student", "learning.preview_as_student"],
  ["homework.view", "homework.view"],
  ["homework.assign", "homework.assign"],
  ["learning.placement.assign", "homework.assign"],
  ["homework.submit", "homework.submit"],
  ["practice.attempts.submit", "homework.submit"],
  ["billing.view", "billing.view"],
  ["billing.summary.read", "billing.view"],
  ["billing.adjust", "billing.adjust"],
  ["billing.adjustments.create", "billing.adjust"],
  ["billing.settings.update", "billing.adjust"],
  ["billing.admin.read", "payments.view"],
  ["billing.reminders.manage", "payments.manage"],
  ["payments.view", "payments.view"],
  ["payments.checkout.create", "payments.view"],
  ["payments.history.read", "payments.view"],
  ["payments.status.read", "payments.view"],
  ["payments.manage", "payments.manage"],
  ["crm.access", "crm.access"],
  ["schedule.view", "schedule.view"],
  ["schedule.lessons.read", "schedule.view"],
  ["schedule.followups.read", "schedule.view"],
  ["schedule.manage", "schedule.manage"],
  ["schedule.lessons.manage", "schedule.manage"],
  ["schedule.followups.manage", "schedule.manage"],
  ["notifications.view", "notifications.view"],
  ["notifications.user.read", "notifications.view"],
  ["notifications.user.manage", "notifications.view"],
  ["notifications.manage", "notifications.manage"],
  ["notifications.admin.read", "notifications.manage"],
  ["notifications.admin.manage", "notifications.manage"],
  ["search.ui", "search.ui"],
  ["word_cards.train", "word_cards.train"],
  ["words.sessions.complete", "word_cards.train"],
  ["word_cards.demo_train", "word_cards.demo_train"],
  ["word_cards.manage", "word_cards.manage"],
  ["words.cardSets.manage", "word_cards.manage"]
] as const satisfies readonly (readonly [string, CanonicalPermission])[];

export const permissionRegistry = {
  canonical: canonicalPermissions,
  legacyAliases: legacyPermissionAliases,
  runtimeCompatibility: runtimeCompatibilityPermissions,
  runtimeOnly: runtimeOnlyPermissions,
  deprecated: deprecatedPermissions,
  rbacAuthoritativeAliases: rbacAuthoritativePermissionAliases
} as const;
